### ISSUE TITLE
Upgrade intl package dependency to 0.19.0

### ISSUE THREAD

**Issue by BigAppsAndroid1** [Zsmerritt/Flutter_AWS_CloudWatch#12]
In Flutter version 3.22.0 intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK, so aws_cloudwatch doesn't match this requirement.

Thanks.

**Comment by Zsmerritt** [comment]
I have resolved the dependency in the most recent version. Please try version 1.0.1
