### ISSUE TITLE
Error when logging for a region different than 'us-west-2'

### ISSUE THREAD

**Issue by rafaelpbrasil** [Zsmerritt/Flutter_AWS_CloudWatch#3]
Utilizing the region 'us-east-1' i receive the error:
> {__type: InvalidSignatureException, message: Credential should be scoped to a valid region, not 'us-west-2'. }

But when utilizing the 'us-west-2' region i got this error  (as expected)
>  {__type: ResourceNotFoundException, message: The specified log group does not exist.}

**Comment by Zsmerritt** [comment]
Looks like I accidentally left in a hardcoded `us-west-2`  
Ill get it fixed later today and push out a new version

**Comment by Zsmerritt** [comment]
This issue should be fixed in version 0.1.7
Thanks for bringing it to my attention :)
