### ISSUE TITLE
The version 1.7.0 fails to build

### ISSUE THREAD

**Issue by rafaelpbrasil** [Zsmerritt/Flutter_AWS_CloudWatch#4]
due to removal of nullsafe args i cannot build the 1.7.0 version of the plugin

**Comment by Zsmerritt** [comment]
I pushed the wrong branch to the repo. Thats my bad. Ill get it fixed in a couple hours. Sorry about that

**Comment by Zsmerritt** [comment]
Ok this should be fixed in 0.1.8  
Let me know if you run into anything else :)
