### ISSUE TITLE
Cannot log to existing stream

### ISSUE THREAD

**Issue by khamidjon-khamidov** [Zsmerritt/Flutter_AWS_CloudWatch#6]
I am trying to log to an existing stream. But it is throwing `CloudWatchException - type: ResourceAlreadyExistsException, message: The specified log stream already exists` error.

**Comment by Zsmerritt** [comment]
Can you provide a little more context around what was happening when this error occurred?  
Did some messages get through and then none after this error occurred?  
Are messages still appearing online but this error is occurring?   
Do you have any steps to reproduce this issue?

**Comment by khamidjon-khamidov** [comment]
1. When I run the first time, I created a stream with name 'foo1'. The stream created. Good. But, on the second run instead of writing to existing stream, it is throwing above exception.
2. No messages occurred the second time(first time it did). It doesn't write to cloud the second time.
3. How I instantiated the object: 
 ```
_cloudWatchHandler = CloudWatchHandler(
          awsAccessKey: _AWS_ACCESS_KEY_ID,
          awsSecretKey: _AWS_SECRET_ACCESS_KEY,
          region: _REGION,
          delay: Duration(milliseconds: 200),
        );
```

Here how I write to the stream:

```
_cloudWatchHandler.log(
        msg: msg,
        logGroupName: _LogGroup,
        logStreamName: logStreamName,
      );
```

**Comment by Zsmerritt** [comment]
Thanks for the info! I appreciate it. I think I understand where the error is occurring. 

I originally wrote this package to log individual user sessions where the log stream name contained a timestamp and was different every session. Adjusting it to work with a static log stream name shouldn't be difficult. I'll put out a patch tonight or tomorrow. 

Thanks for bringing this to my attention :)

**Comment by khamidjon-khamidov** [comment]
Welcome). Would really appreciate if you could release this feature)

**Comment by Zsmerritt** [comment]
Give it a shot with version 0.4.5 and let me know if that fixes the issue

**Comment by khamidjon-khamidov** [comment]
cool thank you!

**Comment by Zsmerritt** [comment]
Did that solve your issue?

**Comment by khamidjon-khamidov** [comment]
Thank you very much! It is perfectly working!
